### ISSUE TITLE
Arm's Reach option

### ISSUE THREAD

**Issue by dineshm72** [Saibot393/Rideable#10]
First, thanks for implementing the "move while riding" option.

I have noticed a few issues / quirks.  I'll log each as a separate issue.

First one: the documentation refers to an extra option to use the Arm's Reach distance for mounting.  I have Arm's Reach installed, but do not see any option for it.

<img width="838" alt="image" src="https://github.com/Saibot393/Rideable/assets/2231877/b48b2151-e221-4d0a-8eb3-f935b65061ec">

**Comment by Saibot393** [comment]
Thank you for all the bug reports, they are really helpfull.

Regarding this bug:
There seem to be two different arms-reach modules:
1. [arms-reach](https://foundryvtt.com/packages/arms-reach)
2. [foundryvtt-arms-reach](https://foundryvtt.com/packages/foundryvtt-arms-reach)
Do you have the first one installes?
Rideable currently only supports the second module, but i will try to add support for the first one in v.2.0.0

**Comment by Saibot393** [comment]
Anyway, if the problem was indeed the confusion between the two arms reach modules, it should now work correctly with v2.0.0

**Comment by dineshm72** [comment]
You are correct, I had the first one installed.  (Didn't even know about the second one.)

Appreciate the fix, I did see it in 2.0.  Though because of the other issue I logged I couldn't actually test it as actually working, but I'll assume it does unless otherwise noted later.
