### ISSUE TITLE
Hostile setting not respected

### ISSUE THREAD

**Issue by dineshm72** [Saibot393/Rideable#11]
When the module is set not to allow mounting enemies, the setting appears not to be respected.

<img width="691" alt="image" src="https://github.com/Saibot393/Rideable/assets/2231877/6d9b79b4-c737-42f0-b9c3-29dd7396c4e7">

**Comment by Saibot393** [comment]
You seem to be logged in as a GM, judging from the screenshot. In this case the behaviour is expected as GM can ignore this setting.
Could you try to log in as a player and tell me if the setting works for you?

**Comment by dineshm72** [comment]
D'oh, you're totally right.  Logged in as a player this works as expected.  My bad!
