### ISSUE TITLE
Riders can move freely has trouble with arrow movement

### ISSUE THREAD

**Issue by dineshm72** [Saibot393/Rideable#12]
Using a 2x2 "mount" and a 1x1 rider, you can use the arrow keys to move around on the mount up and down and diagonally, but not left to right.

e.g. in the picture below, the up and down arrow keys will move the rider up and down on the mount.  Hitting up and left arrow keys simultaneously will move the rider from the bottom left to the top right space.  But hitting just the right and left arrow keys will not move the rider.

<img width="105" alt="image" src="https://github.com/Saibot393/Rideable/assets/2231877/e55593e5-6cb4-4577-915b-8c9d465d6d0d">

**Comment by Saibot393** [comment]
Yes there was a typo in my code, ups. It will be fixed in v.2.0.0

**Comment by Saibot393** [comment]
Now fixed with v2.0.0
