### ISSUE TITLE
Mounting when "Rider can move freely" does not snap to grid

### ISSUE THREAD

**Issue by dineshm72** [Saibot393/Rideable#13]
Possibly this isn't a bug but just a design choice, but it seems wrong to me.

When a grid is in place, tokens will snap to them (at least in my settings, possibly this is not the default case, though I think it is).

When mounting a mount which has the "riders can move freely" option set, the rider gets moved onto the mount, but the movement stops in an awkward position, rather than snapping to one of the available grid positions on the mount.

<img width="123" alt="image" src="https://github.com/Saibot393/Rideable/assets/2231877/72d5b91f-4fd5-4010-8bd5-640b43ada875">

If you then try to manually move the rider token, it will snap into the grid properly.

**Comment by Saibot393** [comment]
I forgot about grids, since all my games use gridless maps. In v.2.0.0 correct snapping will be implemented (at least for square grids)

**Comment by Saibot393** [comment]
Now improved with v2.0.0

**Comment by dineshm72** [comment]
I am not seeing any difference in 2.0.1 in v10, gridded.  It continues to not snap to the grid, and stops the token half on and half off the mount somewhere around the boundary.

**Comment by Saibot393** [comment]
It seems the previous enhancement i implemented does not work for Foundry v10 (which is rather strange). I will look into it

**Comment by Saibot393** [comment]
The bug is now fixed with v2.1.0, thanks again for all the bug reports and suggestions.
