### ISSUE TITLE
Cannot mount more than 2 1x1 tokens on a 2x2 mount when not moving freely

### ISSUE THREAD

**Issue by dineshm72** [Saibot393/Rideable#14]
No max riders set (-1).  Move freely not set.

Mounting 1 rider works fine, and the rider is placed in the center.

Mounting 2 riders works fine, and the riders are moved side by side (left to right), but centered (top to bottom).

Once I add a third rider, though, the rider gets the elevation added, but doesn't get moved to the mount.  And then all three riders seem to get disconnected from the mount (and locked in place on the canvas).  If you move the mount, they do not move with it.

I do have z scatter and some other modules that may be interfering, so I will try testing without them just to double check when I get a chance, but I have a game starting now and can't do so.

<img width="159" alt="image" src="https://github.com/Saibot393/Rideable/assets/2231877/1b23bd8b-d314-405a-baa0-8b5c5827aaeb">

<img width="142" alt="image" src="https://github.com/Saibot393/Rideable/assets/2231877/74df3a19-ac54-4c3c-8654-ecd9436f6d20">

**Comment by Saibot393** [comment]
There was a typo in my code (again). Will be fixed in v.2.0.0.

Thanks again for all the bug reports.

**Comment by Saibot393** [comment]
Now fixed with v2.0.0

**Comment by dineshm72** [comment]
This works now.  But the stacking of the tokens is not ideal.  The first one goes in the center.  The second makes them side by side.  But after that the tokens just get stacked in a tighter and tighter spread between those same two ends, at least using 1x1 tokens on a 2x2 mount.

example, this is 4 tokens on a 2x2 mount.

<img width="220" alt="image" src="https://github.com/Saibot393/Rideable/assets/2231877/3129a3e7-60ed-42a6-8970-7c6533d4cb4b">

**Comment by Saibot393** [comment]
I will split this into a new issue since it is not directly related to the previous bug and closer to a new feature
