### ISSUE TITLE
Version 2.0 issues

### ISSUE THREAD

**Issue by dineshm72** [Saibot393/Rideable#15]
Unfortunately, with version 2.0 nothing is working for me any more.

When trying to mount, I get this error.

<img width="535" alt="image" src="https://github.com/Saibot393/Rideable/assets/2231877/44024f2e-8400-4329-896d-4b288e81ad97">

It will set the elevation, but nothing else.

If I try to dismount, I get this error (which of course could be spurious because of the first error, but I include it for completeness): 

<img width="531" alt="image" src="https://github.com/Saibot393/Rideable/assets/2231877/2c6775e5-428c-4469-a858-d542c7af28a7">

I am in Foundry 10.291, dnd5e 2.2.1, Rideable 2.0.0.

Here are my options:

<img width="819" alt="image" src="https://github.com/Saibot393/Rideable/assets/2231877/af4aa8f1-e8fd-4a3b-b3f9-c4d69436b4ed">

**Comment by dineshm72** [comment]
Once the above happens I can't even get the elevations to change any more, something is well and truly borked.  Hopefully it's not a permanent flag issue (or there is some macro I can run to get everything back to working once things are fixed).

**Comment by Saibot393** [comment]
Just released a preliminary hotfix (v2.0.1) that should take care of this (and learned that i should test major changes on FOundry v10 before releasing...)

**Comment by dineshm72** [comment]
Seems to be working now, thanks!  (I do have some more bug reports to file, and updates to earlier ones.)

**Comment by Saibot393** [comment]
Good to hear that this bug is fixed now. I will have a look at the other issues. Thanks again for all the bug reports.
