### ISSUE TITLE
Mounting is per scene but status effects are global

### ISSUE THREAD

**Issue by spaceotter** [Saibot393/Rideable#21]
If you have an actor with linked tokens (like a player character) and mount them in two separate scenes, they wind up getting the mounted status effect twice, or if mounted in only one scene, they have the mounted effect in the scene where they aren't mounted.

**Comment by Saibot393** [comment]
They way effects synchronize between scenes is inherent to the system, so i will not be able to fix the problem with tokens having the mounted effect in other scenes. I will however look into the double applied mounted effect, that should be preventable.

**Comment by Saibot393** [comment]
The mounted effects will now only be applied once with v2.5.2
