### ISSUE TITLE
Familiar: option to change the corner where the familiar is located

### ISSUE THREAD

**Issue by franckflo** [Saibot393/Rideable#23]
I love this module, many thanks for creating it and making it so user friendly and updated.

I thin he title says it all: by default the familiar stays on the top-left corner of the token it is riding. This can cover the status markers on the marker (I use a halo status marker). 

Could it be possible to add an option in Rideable which allows to choose what corner the familiar will stay at? 

Thanks !

**Comment by Saibot393** [comment]
Glag you enjoy the module. I will add an option for the starting corner of familiar mounting in the next update.

**Comment by franckflo** [comment]
Wonderful, thank you !

**Comment by Saibot393** [comment]
This feature has now been added with v2.6.0

**Comment by Saibot393** [comment]
This feature has now been added with v2.6.0
