### ISSUE TITLE
Add Configure Controls option to manage GM and Player controls

### ISSUE THREAD

**Issue by Spuznik** [Saibot393/Rideable#26]
Ability to change the controls to suit players preference, additionally a method to call the PickLock, UseKey, BreakLock functions to allow for a gui popup on a player left clicking on a door

**Comment by Saibot393** [comment]
Good idea, i will look into it for the next update, atleast the hotkeys should be easy to do. (Also, you probably meant to post the issue here: [Lock & Key](https://github.com/Saibot393/LocknKey))

**Comment by Saibot393** [comment]
Key bindings and an optional popup menu for lock use have been added with v1.9.0
