### ISSUE TITLE
Set the height of the Rideable Token 

### ISSUE THREAD

**Issue by Spuznik** [Saibot393/Rideable#27]
Ability to specify the height of the token on an individual basis in the rideable tab of the token . Not use the Riding Height or Use token height in the setting.

![image](https://github.com/Saibot393/Rideable/assets/142272986/228b50a6-202c-4d2c-a8cf-db84c082eaf4)

This would allow for multiple scenarios where the creature is taller than the standard creature, so the token riding will be higher and visible over shorter versions.

BTW I love this module, it has made combat so much better as player can target mount or rider. You are a legend!

**Comment by Saibot393** [comment]
Good idea, i will add in to the next update. Glad you enjoy the module.

**Comment by Saibot393** [comment]
The token setting Custom riding height has been added with v2.7.0
