### ISSUE TITLE
Familiar mounting via hovering and pressing 'J' no longer working

### ISSUE THREAD

**Issue by Pyroman2xxx** [Saibot393/Rideable#29]
As of the 2.7.0 release, familiar mounting no longer works by selecting the familiar, hovering the ridable token, and pressing 'J'.

Console error generated when this happens:
Uncaught (in promise) ReferenceError: undefined. vTarget is not defined
[Detected 1 package: Rideable]
    at MountingScript.js:164:89
    at Array.filter (<anonymous>)
    at MountingManager.RequestMount (MountingScript.js:164:32)
    at MountingManager.MountSelected (MountingScript.js:114:19)

**Comment by Saibot393** [comment]
Should be fixed with v2.7.1, thanks for the report and especially the included console error

**Comment by Pyroman2xxx** [comment]
Thank you for the quick fix!
