### ISSUE TITLE
Keybinding for Unmount

### ISSUE THREAD

**Issue by nemthe** [Saibot393/Rideable#3]
Is there an option aside from activating Rider movement to unmount to unmount tokens?

**Comment by Saibot393** [comment]
Yes:
-If you are the owner of the riding token you can simply press the "n" key or use the "UnMount" macro while having the token selected.
-If you are the owner of the ridden token (or rather the mount) you can target the riding creature while having the ridden token selected and press the "n" key or use the "UnMount" macro to unmount the targeted creature
