### ISSUE TITLE
Change the position of the grappled token

### ISSUE THREAD

**Issue by DevEsquilo** [Saibot393/Rideable#32]
When using Grapple the grappled token is always below the grapper, is there a way to change it so it can always stay behind the grappler no matter which direction it moves?

**Comment by Saibot393** [comment]
Technically you could use the module [Auto-Rotate](https://foundryvtt.com/packages/autorotate) (not sure if it works in v11) since the position of the grappled tokens will rotate with the grappling token. But i will look into it and see if i can maybe implement an independent automation for that in one of the next updates.

**Comment by DevEsquilo** [comment]
Auto-Rotate works with v11 (at least with grapple and mount), the grappled token will always be in front, as if it were holding it hostage, if you add this rotation function in the future, it could be interesting to have an option to know if the token is being grappled from the front (as a hostage) or from behind (as if dragging an injured player through the floor)

**Comment by Saibot393** [comment]
Good idea, i will probably add it as a setting similar to the Rider positioning option, maybe with an optional key to toggle between them

**Comment by Saibot393** [comment]
I have just released v2.8.1 which adds a placement option for grappled tokens

**Comment by Saibot393** [comment]
I dont think there is much more i can do with feature, at least nothing that can not be done in combination with Auto-Rotate, i will therefore close this issue for now. Should you have any other suggestions/request feel free to reopen this issue or open a new one.
