### ISSUE TITLE
2.9.0 makes Token & Tile Configuration windows unnecessarily oversized

### ISSUE THREAD

**Issue by GambetTV** [Saibot393/Rideable#33]
Not sure why this would be, but for some reason Rideable makes various configuration windows much larger than they have to be.

I've attached numerous screenshots, but it seems to affect both Token and Tile configuration windows, but it affects different tabs within the same window differently, so they'll bounce all over the place in wildly different sizes that can make working with them a bit tedious.

![image](https://github.com/Saibot393/Rideable/assets/72000497/5a88adbf-47b9-43ce-bc11-8ddd35880e55)
![image](https://github.com/Saibot393/Rideable/assets/72000497/e1ee56e1-7e42-42fc-a17a-c37ae3efe7ef)

**Comment by Saibot393** [comment]
Fixed wtih v2.9.1, thanks for notifying me.
The reason this happened was, that i forgot to delete some test code with which i tried to fix a little ui bug which causes tabs to be outside of the the window if too many are added (which will happen with a planned release for another module of mine)
