### ISSUE TITLE
Toggling combat state makes tokens mount each other

### ISSUE THREAD

**Issue by Ghostdesu** [Saibot393/Rideable#34]
Foundry v11.308
PF2e 5.4.4
Rideable 2.9.2

Tested with no unnecessary modules except for Module Management+

When the Mount button is set to be displayed on the right, selecting multiple tokens and using the Toggle Combat State button makes them try to mount with the same behavior as the actual Mount button. 

Similar behavior happens if the button is set to the left and another module adds its button on the left. (For example, Mass Edit).

**Comment by Saibot393** [comment]
Thanks for the bug report, should be fixed with the new v2.9.3
