### ISSUE TITLE
Feature Request: Ignore mounting control tokens for prefab vehicles using Token Attacher

### ISSUE THREAD

**Issue by baileywick** [Saibot393/Rideable#37]
When using vehicles that are a series of attachments to a control token (using the Token Attacher module), the control token can itself become mounted to the vehicle tile if it collides with a tile that allows for mounting upon entry. 

I would suggest a field that lets us list any tokens (or token keywords) we wish to exclude from the auto-mounting

**Comment by Saibot393** [comment]
Good idea, i will look into it for the next version

**Comment by Saibot393** [comment]
I have added blacklist for Mount on Enter with v2.10.0

I have also added a safety check to prevent "Riding loop" created in combination with Token Attacher. I am not 100% sure that it will catch every possible combination but it should at least prevent the most common forms.

**Comment by baileywick** [comment]
Amazing!
