### ISSUE TITLE
Feature request: Ability for effect on the mount when mounted by a rider

### ISSUE THREAD

**Issue by T-Whiz** [Saibot393/Rideable#40]
Would it be possible to include a way for an effect to be applied to a mount while it’s mounted by a rider? This would allow a mount to benefit from effects in situations such as when using the Mounted Combatant feat in dnd5e.

**Comment by Saibot393** [comment]
So something like a new text field where riders can enter the effects they give their mount? Sure no problem.

**Comment by p4535992** [comment]
Not sure if is something to put in this module there are to many differences between  Pf2e effect management and the other systems. A better solution maybe is to put some hook on the module to let the single system integrate some macro with it.

**Comment by Saibot393** [comment]
I will for now add something similar to the already exisitng riding effects that are applied to riders of certain mount. These  currently only work for Pf2e or with DFreds CE. There are allready hooks for "Mount" and "UnMount"

**Comment by Saibot393** [comment]
I have just released v1.12.0 which adds the token setting Mount effects
