### ISSUE TITLE
Feature Request: Disable riding height adjustments when mounting/dismounting.

### ISSUE THREAD

**Issue by Codious888** [Saibot393/Rideable#43]
It would be nice if there were a way to disable adjusting the height of a token that is mounting/dismounting a rideable token/attached tiles. 

For example, on a spelljamming ship with three different levels, and stairs/ladders going between the levels, the height adjustment seems to be based on the control token's height which is in the middle layer (10ft) in this example. So if a token enters the ship from the cargo hatch(0ft) and mounts, the module teleports him to the mid level(10ft). Likewise if You mount on the midlevel deck (10ft) then move up to the third level castle deck (20ft) then dismount from there, the module will teleport you through the floor back mid level (10ft).

A simple solution would be to have an option to to disable changing the rider token's height at all when it is mounting/dismounting, and just keep the token at what ever elevation it is at currently.

**Comment by Saibot393** [comment]
I will add an option for that in the next version

**Comment by Saibot393** [comment]
This feature has been implemented with v2.15.0

**Comment by Codious888** [comment]
Awesome. Thank you!
