### ISSUE TITLE
Mounting Position Suggestion

### ISSUE THREAD

**Issue by XXDarrienX** [Saibot393/Rideable#48]
Is it possible to add another position for mounting to the back of the token?

I am using this for my scifi setting to mount crew members to ships to they can use their vehicle scaled abilities but even with the scaled actor size they can sometimes cover the ship token. I would like to keep from having to scale the ship token sizes up too much for this if I can help it, especially if its a small ship
Example #1
![image](https://github.com/Saibot393/Rideable/assets/28017703/8c63a8f2-b80e-4d00-a048-0ab7f2f837e7)

So in this image as an example can it be possible to have them be mounted in the back of the token? Sort of like this in the second picture? Its a rough example

![image](https://github.com/Saibot393/Rideable/assets/28017703/e5562aa8-d457-443b-9e15-a9004e399d4a)

**Comment by Saibot393** [comment]
Sure that shouldn't be a problem, i will add it with the next release.

**Comment by Saibot393** [comment]
I have added a Row top and Row bottom option for the rider Placement with v2.15.10

**Comment by Saibot393** [comment]
Btw. since a few updates ago you can also set the riding height to 0 and the tokens should still stay atop the mount, in case the "+5 meters" above the tokens bothers you
