### ISSUE TITLE
Riders cant Control tokens

### ISSUE THREAD

**Issue by wreckluse94** [Saibot393/Rideable#50]
I'm trying to make my riders control the tokens independently. The closest I was able to get was by modifying ownership, but the rider token does not move with the mount and instead stays in place. I like this module and dont want to resort to token attacher, as it defeats the purpose of me downloading this in the first place.

This is only an issue with the player screen and not the DM screen. Everything works fine on my end, but testing it with the players seems to either make both tokens unmoveable or it makes just the mount move. Thank you for your time :)

**Comment by Saibot393** [comment]
Do any errors show up in the console(F12)?
Do, should they be enabled, the message popups for mount/unmount show up?
What is the players "Rider movement" setting set to?
Could you send me screenshot the rideable settings of the ridden token?

**Comment by Saibot393** [comment]
I will assume that this problem was "accidentally" solved with one of the last updates and close it soon unless i hear back on it.

**Comment by wreckluse94** [comment]
Yes! I'm incredibly sorry about not responding sooner. I\ve been wrapped up
with personal stuff. Thank you very much for checking in and I appreciate
your time.

**Comment by Saibot393** [comment]
No worries, good to hear that everything works.
