### ISSUE TITLE
[Enhancement] Ability to control scale of "shrinking" rider

### ISSUE THREAD

**Issue by weepingminotaur** [Saibot393/Rideable#51]
I like the ability to shrink the rider of a mount, but the shrinking is almost too much sometimes, relative to the token. It would be great to be able to control the rate of shrinking (a percentage of the token's size or something) so mounted characters don't look tiny on their mounts.

**Comment by Saibot393** [comment]
I will add a slider for the scaling.

**Comment by Saibot393** [comment]
I have added the world setting Adjusted rider size factor with v2.16.3. Foundry however only allows certain sizes for tokens, so for 1x1 tokens there is only a very limited amount of possible choices for the size ( i think it's basically only 1 or 0.5 of the original size).
