### ISSUE TITLE
Is there a way to know when know when an actor is riding a mount?

### ISSUE THREAD

**Issue by MDtheSimp** [Saibot393/Rideable#52]
mainly wanna know if it would be possible to use the fact that a pc is riding a mount for a predicate on certain feats features etc.

**Comment by Saibot393** [comment]
Depends on what exactly you want to do, there  is a bit of api under `game.modules.get("Rideable").api.RideableFlags`. Depending on what exactly you want to do something like `isRider`, `isRiddenby`, or `RiddenToken` might work for you.

**Comment by MDtheSimp** [comment]
> Depends on what exactly you want to do, there is a bit of api under `game.modules.get("Rideable").api.RideableFlags`. Depending on your use case, something like `isRider`, `isRiddenby`, or `RiddenToken` might work for you.

Mainly have a feature that increases the damage of a strike while you are on a mount and wanted to know if it would be possible to have only be in effect while the pc is riding a mount.

**Comment by Saibot393** [comment]
Which system are you using?

**Comment by MDtheSimp** [comment]
Ah my bad it's pf2e

**Comment by Saibot393** [comment]
Rideable can apply effects on mount, theoretically it should be possible to add somekind of custom flag to such an effect and make thet feature be conditional on the presence of that flag. I will look into it and see if i can create an example.

**Comment by Saibot393** [comment]
There is a good chance, that there is a smater or easier way to do this, but this should work:

1. Create a new actor trait called e.g. "Riding" (under "configure settings">"Manage Homebrew Elements")
2. Create a new custom mounted effect (or just copy the one in the compendium) and add this rule element to it `{"key":"ActorTraits","add":["hb_riding"]}`
3. Add this into the predicate field of the effect taht should only be active while riding: `["self:trait:hb_riding"]`
