### ISSUE TITLE
Allow custom positioning on the rideable object

### ISSUE THREAD

**Issue by picollo-24** [Saibot393/Rideable#53]
Currently when you move token on top of rideable object, it will be moved to predetermined position on the object. 
How hard would it be to make token remember position relative to the object and stick to it whenever object moves? Let's say I  have cart token. I'd love to be able to attach horse token to the front of the cart, and for it to stick there. Then let me move my PC on the cart itself, so it will look like it's sitting on the cart, and not being placed in random place inside it.
It;s not a bug per se, it's rather suggestion for functionality.

**Comment by Saibot393** [comment]
Should be easy enough to do, i will look into it for the next feature update.

**Comment by Saibot393** [comment]
I have added the riding positionen "Mounting position" with v2.17.0
