### ISSUE TITLE
Question : how to "un-grapple" ?

### ISSUE THREAD

**Issue by MastaGooz** [Saibot393/Rideable#54]
It may sound stupid but I looked everywhere and I don't find how to un-grapple a token.

I used : 
game.Rideable.GrappleTargeted();

Token A grappeled token B, but then I have no clue how to un-grapple token B.

**Comment by Saibot393** [comment]
While having the grappeling token selected you can either hover or target the grappled token and use the same macro/key you sued to grapple the token to release it.

**Comment by MastaGooz** [comment]
Hum. It's does not work for me with the macro and the key is returning ''this token IS locked''. I'll do some deeper to check.

**Comment by Saibot393** [comment]
The "this token is locked" message is from lock & key, the ridden token is probably locked by lock & key, meaning, no one can unmount or mount this token currently

**Comment by MastaGooz** [comment]
I know but the token is not locked nor set as lockable. This is maybe the bug on lock n key where tokens behave as locks again. I'll do more testing asap and I let you know.

**Comment by MastaGooz** [comment]
I did more testing, and it is the same Lock & Key bug that I reported last time : token act as they are locked even if they are not supposed to. So you can shut this topic since it's not about rideable (when I turn L&K down, it works perfectly).

**Comment by Saibot393** [comment]
I really need to find this bug, sorry that it pops up so often
