### ISSUE TITLE
Player's Mount Control Issues

### ISSUE THREAD

**Issue by EchoVG** [Saibot393/Rideable#55]
Foundry version: 11.315
DnD5e version: 2.4.1
Rideable version: 2.17.2

I'm having trouble getting my players to be able to move tokens they mount. As the DM, I can move the mounted token and they move fine, but when I join the game as the player, they can move the mounted token only if they have ownership, but when they move the token they detach and move just the mounted token. Their PC token stays in the original position.
Players are also unable to mount tokens themselves, I as the DM have to mount and unmount them.

**Comment by Saibot393** [comment]
When testing the module as a player, is a GM account online?

**Comment by EchoVG** [comment]
There was not. Upon testing this issue with a DM account online, it seems to be working as intended!

**Comment by Saibot393** [comment]
Good to hear. Small explanation why a GM account is necessary:
Some of the things rideable does (e.g. moving a token a player doesn't own) are simply not possible with foundry. The data that would have to be changed by a player is protected by foundry if they don't own the token. Instead rideable basically requests the GM account to make the appropiate movements for the player.
