### ISSUE TITLE
PF2e Console Warning

### ISSUE THREAD

**Issue by ottyn** [Saibot393/Rideable#57]
Seeing the following warning message in console with the latest version of PF2e v5.12.6 when accessing the Prototype Token settings.

![image](https://github.com/Saibot393/Rideable/assets/97130150/49898402-8741-4926-84e5-4675db1654fb)

**Comment by Saibot393** [comment]
The warning appears due to some settings being unset (all the empty inputs). Rideable will use default values for all these settings. The warnings can be ignored (or at least i never encountered a problem with them).
