### ISSUE TITLE
Request: allow riders to move within boundaries of ridden/mount

### ISSUE THREAD

**Issue by dineshm72** [Saibot393/Rideable#6]
This might be outside of scope, but if not it would be pleasant for vehicle use.

Right now it is difficult or impossible to create a vehicle which can move, transporting all the riders on it; but also allow the riders to somewhat independently move within the boundaries of the mount.  

As an example, if you have a ship with a deck.  Whenever the ship itself moves, all the riders on the ship should move with the same translation and rotation, to remain in the same place relative to the ship.   But separately and independently, it would be nice if the riders on the ship could move around within the confines of the ship (i.e. on the deck).  This would give every player the ability to control their tokens on the vehicle, while still allowing someone (GM, a single player, or perhaps all players) the ability to also move the vehicle on the map, moving all players along with it.

Ideally players cannot move outside of the vehicle dimensions (set automatically as the vehicle's size?  Or maybe some way to independently configure it), but perhaps optionally if they move outside of the boundary they dismount, similar to current behavior on any move.

Thanks for considering!

**Comment by Saibot393** [comment]
This is actually something i had already considered. It is however a somewhat more complex feature that will take a bit more time and testing to get right. I will probably add it within the next weeks, but the next updates will focus on smaller features and compatibility.

**Comment by Saibot393** [comment]
This feature is now available in v1.6.0. It has to be toggled on in the token settings of the ridden token.
