### ISSUE TITLE
Rideable not working for PF2

### ISSUE THREAD

**Issue by RogerSWD** [Saibot393/Rideable#60]
Hello, I have the token that is the mount configured in the rideable tab to be rideable and mount on enter. Not working. Pressing M does noting either?

**Comment by Saibot393** [comment]
A few questions:
1. Are there any errors in the console (F12) when trying to mount?
2. Do any messages popup above the tokens (assuming that rideable setting "Message popups" and the core setting "Scrolling Status Text" is active)?
3. Could you send me a picture of the the mounts rideable settings tab?

**Comment by Saibot393** [comment]
The above message is not related to rideable. Could you send me screenshot of the rideable settings of the mount?

**Comment by Saibot393** [comment]
is this problem still present?
