### ISSUE TITLE
'Riders Can Move Freely' Setting seems to have broken in upgrade to v2.18.0

### ISSUE THREAD

**Issue by VonKeebler** [Saibot393/Rideable#61]
Example, I have a 2x3 Truck token set to 'Rideable', 'Mount on Enter', and 'Riders Can Move Freely'. I have "Unmount Rider" on move setting set as well. The tokens used to mount if they entered the space of the truck, be able to move about the cabin, and then unmount if they were moved outside the bound of the truck. 

Since this upgrade, I am unable to move the token at all once mounted and must use the hotkey to dismount. If I turn off the 'Riders Can Move Freely', they can move again but dismount if they move to another position, regardless of if it is inside or outside the trucks boundary.

Tried turning routinglib on and off and few other settings.

![image](https://github.com/Saibot393/Rideable/assets/16258090/ac5e8b26-2bd5-45aa-a153-fc55721a04b4)

**Comment by Saibot393** [comment]
Should be fixed with the new v2.18.1

**Comment by VonKeebler** [comment]
Thanks! The absolute best mod for car chases, hands down.

**Comment by Saibot393** [comment]
Happy to hear that the module is of use. Fun fact, the bug was pretty much a missing "()"
