### ISSUE TITLE
Rideable not working only for players pf2e

### ISSUE THREAD

**Issue by ChrisPMohr** [Saibot393/Rideable#65]
I just installed Rideable and am having an issue using the module in a player account, but it works fine on a GM account. Using either the mount hotkey, mount button, or mount macro have no effect when logged in as a player account.
I have disabled all modules other than Rideable, routinglib, and the module for the adventure path I'm using.
I've confirmed that the player is the owner of both the mount and rider actors.

There's no errors in the console logs, but I do notice that if I right click on the mount actor, I see a log from MountingScript.js:455:13 which differs whether I'm logged in as the player or GM. This is from when I have both actors on the same scene, but not mounted.

As a GM I see:
```
Array [ {…} ]
0: Object { constructed: true, name: "Rosa", displayName: 20, … }
length: 1
<prototype>: Array []
```
(just the mount actor)

but as a player I see:
```
Array [ {…}, {…} ]
0: Object { constructed: true, name: "Rosa", displayName: 20, … }
1: Object { constructed: true, name: "Esmera", displayName: 20, … }
length: 2
<prototype>: Array []
```
(both the mount and the actor)

Module settings:
Player:
![player module settings](https://github.com/Saibot393/Rideable/assets/4406927/fa56e713-04bf-4a20-a8c9-f44cb45f6f8b)

GM:
![gm module settings 1](https://github.com/Saibot393/Rideable/assets/4406927/0471ccbb-b95f-4cea-b9c9-38e40ac4dfa0)
![gm module settings 2](https://github.com/Saibot393/Rideable/assets/4406927/5440012c-13d6-4491-b568-3724cf2343a7)
![gm module settings 3](https://github.com/Saibot393/Rideable/assets/4406927/556181ee-a87f-45dd-b22c-1ba7c1815073)

Foundry: version 11.315
Rideable: version 2.19.5

**Comment by Saibot393** [comment]
For Rideable to work a GM has to be logged in.

**Comment by ChrisPMohr** [comment]
That would explain it. I was testing by myself, switching between player
and GM accounts. Thanks!

**Comment by Saibot393** [comment]
Note that a lot of automation modules that allow players to do things they normally couldn't, use similar ways of "outplaying" foundrys permission limitations, and therefore need a GM to be online
