### ISSUE TITLE
feature: Allow for fixed offset positioning of rider

### ISSUE THREAD

**Issue by digitalpacman** [Saibot393/Rideable#66]
I am attempting to use isometric maps and tokens.  When doing this, the positioning of ridable puts them in really weird spots.  It could work, good enough, if I could specify a fixed offset for riders.  I would just do this for each individuals mount.  In this instance, it's simply 1 horse = 1 rider.  An X/Y offset would be great. A button for draggable movement would be stellar.

**Comment by Saibot393** [comment]
I will look into an offset setting. With "button for draggable movement", do you mean being able to set the X/Y offset by positioning a token and saving its position offset as the new offset (similar to the positioning setting supported by e.g. Monks active tile triggers)? If so i will see what i can do in that regard

**Comment by digitalpacman** [comment]
Yeah exactly like that

**Comment by Saibot393** [comment]
I have added a token/tile setting for the riders offset with v2.20.0
