### ISSUE TITLE
Token get connected to the mount token borders instead to be sent to the middle of the mount token at +5 feet

### ISSUE THREAD

**Issue by Damianoatlante** [Saibot393/Rideable#68]
Recently I found that the token wich should go on top of the mount (in the middle of it at +5 feet) when I press M just get connected to the mount token borders. I didn't change any setting and don't know how to go back to the previous mechanic.

FVTT version 11.315
D&D system 3.1.0

**Comment by Saibot393** [comment]
Could you send me screenshot of the ridden tokens rideable settings?

**Comment by Damianoatlante** [comment]
![Screenshot 2024-04-16 191408](https://github.com/Saibot393/Rideable/assets/119633900/29cecf86-8553-4c23-93b3-905bfceafbd8)
![Screenshot 2024-04-16 191432](https://github.com/Saibot393/Rideable/assets/119633900/47cf2ddf-f280-4e4d-8c46-0d7142fc654a)
![Screenshot 2024-04-16 191451](https://github.com/Saibot393/Rideable/assets/119633900/d21e607d-290c-414e-82b6-f068ea1062ed)

**Comment by Saibot393** [comment]
Those seem to be the world/client settings, i need to see the tokens settings (the ones opened when clicking on the cogwheel symbol in the tokens right click hud)
![image](https://github.com/Saibot393/Rideable/assets/137942782/736e8a55-9aa9-4730-a7fb-3f1f1112de5b)

**Comment by Damianoatlante** [comment]
I just find out that If I use the icon of the token UI instead of the M it works correctly

![Screenshot 2024-04-16 191859](https://github.com/Saibot393/Rideable/assets/119633900/c71b8e23-1ede-4b70-b892-e5e1816c308b)

**Comment by Saibot393** [comment]
Are the riders being place on the ridden tokens corners? Can they move freely, once they are mounted?

**Comment by Saibot393** [comment]
could you send me a screenshot of the tokens while riding so i can get a better idea of whats going on exactly?

**Comment by Damianoatlante** [comment]
Those are the token wich I want to link 
![Screenshot 2024-04-16 192642](https://github.com/Saibot393/Rideable/assets/119633900/519ec9c6-5601-4af8-a897-a8e0eef5b843)

This is what happens when I press M 

![Screenshot 2024-04-16 192655](https://github.com/Saibot393/Rideable/assets/119633900/71a91981-38ac-4cbb-b34c-046ec06b4135)

They actually get no link

**Comment by Saibot393** [comment]
Are there any errors in the console (F12) when you to mount the token?

**Comment by Damianoatlante** [comment]
I use to have generic errors like this since I switched to D&D system 3.0 but they are not linked to rideable 
![Screenshot 2024-04-16 193315](https://github.com/Saibot393/Rideable/assets/119633900/d51f58b1-b9ed-4034-a27b-79227834b5c7)

**Comment by Saibot393** [comment]
Could you send me your world file (without all the media data), if you want via discord(saibot5279)? I need to take a closer look to figure that problem out

**Comment by Damianoatlante** [comment]
Is it okey If I send the Data and Packs folder only? (Inside of the world folder ofc)
