### ISSUE TITLE
"Following" Macros

### ISSUE THREAD

**Issue by Bomberman1988** [Saibot393/Rideable#71]
I've tried to make my Animal Companion to follow my ally several times but it never worked, is it some  kind of bug?

What does the "Toggle Following" macro do exactly? It doesn't have  any visual effect so I've no idea of what's supposed to do

**Comment by Saibot393** [comment]
So, how it is supossed to work is like this: Let's say you want token A to follow token B, you select token A, hover over token B (or target token B) and either use the macro or press the toggle follow key (default F). To stop following, hover over an empty region of the map/untarget token A and use the toggle macro or key again.
You can activate the Rideable setting "Message popups" to gain more information (started/stopped following) (you might need to activate the Foundry setting "Scrolling Status text" first).
Should that not work there might be a bug. In this case, are there any erros in the console (F12) upon using the macro/key?

**Comment by Bomberman1988** [comment]
Understood, but the Following macro isn't working, at least not with Animal
Companions. As I said I can't make my AC follow my ally. It says it's
following, but it doesn't move. The Console seems to be ok. Could you check
it out?

**Comment by Saibot393** [comment]
Which following algorithm are you using (Rideable setting "Following algorithm")? If it is set to "Simple path history", installing [routinglib](https://foundryvtt.com/packages/routinglib) and using that instead may fix it. It could also be a module incompatibility, have you tried running [Find the culprit!](https://foundryvtt.com/packages/find-the-culprit/)?
I will look into any possible bug as soon as possible.

**Comment by Saibot393** [comment]
Is this still heppening with the newest versions of rideable?
