### ISSUE TITLE
 Russian localization

### ISSUE THREAD

**Issue by maragondi** [Saibot393/Rideable#72]
Just to make it more comfortable when they say "Заперто!" at the door. I could help with the translation.

**Comment by maragondi** [comment]
Yes, can you give an explanation?
I know English quite well (unlike my players)
But I'm weak in programming.

**Comment by Saibot393** [comment]
Translation are relatively easy and do not really require any programming skills.
The first thing you will need to do is download the english version of the localization file, you can do that here.
To open the file you can really use any kind of text editor but i would recommend notepad++, this editor will give you bit of nice highlighting.
From there you can basically start translating, the text on the left of the ":" (blueish in the screenshot) are the keys and have to be kept unchanged, the text at the right of the ":" (orange in the screenshots) are what you can edit for the translation. 
![image](https://github.com/Saibot393/Rideable/assets/137942782/f5455171-42cb-4dbd-86f6-abd4e55e3d1a)
A few details: 
If you want to use as " " " in the translation you have to write " \" " instead. 
Sometimes things in curved brackets appear in the text, (e.g. {pCheckName}), these will hvae to remain unchanged but can be placed in anywhere within the translated text. They will later during the game be replaced by specific values.
Once you are done you can simply apload the file here and i will release an update containing the translation.
If you have any questions or need any context regarding the text feel free to ask.
I also know that there is quite a bit of text to be translated so if you do not want to translate it all at once you can also give partly translated files anddo further work on the translation whenever you want.

**Comment by maragondi** [comment]
[en.json](https://github.com/Saibot393/Rideable/files/15280319/en.json)

here!

**Comment by Saibot393** [comment]
Thank you very much, the translation is now included with v2.7.9
