### ISSUE TITLE
"Follow" grapple variant doesn't function

### ISSUE THREAD

**Issue by TrofimSelbs** [Saibot393/Rideable#75]
Hey! Love the module. I have been having issues with "Follow" variant of grappling. It applies grappled DF CE, but it doens't follow the grappler. Other methods, such as "inside" & "below" work. I am on v11 of foundry vtt 315, dnd 5e 3.1.1. Could you please look into this? Thank you!

ps: sorry for the quality. GitHub wouldn't allow to upload a bigger file

https://github.com/Saibot393/Rideable/assets/124184162/446a4152-92bb-440b-ac9e-a46b1b10ca51

**Comment by Saibot393** [comment]
There is a bug with following i did not yet have time to track down. That bug (as far as i know) only happens when using the "Simple path history" following algorithm. I think switching to "routinglib" (after installing [routinglib](https://foundryvtt.com/packages/routinglib)) might fix the bug.
Also, glad you enjoy the module

**Comment by TrofimSelbs** [comment]
Is it a module? If yes - then no, I don't use it. I have routinglib though. Additionally, I was able to reproduce this issue with just these modules active

![image](https://github.com/Saibot393/Rideable/assets/124184162/c21bd6e4-efc3-4cab-8815-235ac3dd0249)

**Comment by Saibot393** [comment]
If you have routinglib enabled in the world there should be a world setting called "Following algorithm" in the rideable settings where you can switch to routinglib. The routinglib algorithm is the recommended following algorithm, the simple path history one is mainly intended as a low resource option and in case routinglib isn't availbale after a foundry version update.

**Comment by TrofimSelbs** [comment]
Thank you! Yes, this works. I think I chose it cos it said "resource light" and then forgot. Much appreciated!

**Comment by Saibot393** [comment]
I will try to fix the path history as soon as possible

**Comment by Saibot393** [comment]
I finally got around to fixing the simple path history algorithm for grapple following. Should now be working correctly with v2.21.7

**Comment by TrofimSelbs** [comment]
wow, awesome! will try it out. thank you! it has the same functionality now as routinglib?

**Comment by Saibot393** [comment]
Basically yes. In general i would still recommend routinglib if possible since it will normally find the more effective or smater ways, path finding will require less processing though

**Comment by TrofimSelbs** [comment]
got it. I think I will stick to path, as my players have potatoes for PCs. But if any issues - will change. Thank you for your time, I really appreciate it
