### ISSUE TITLE
Tokens pass through walls while mounted

### ISSUE THREAD

**Issue by zeleni3** [Saibot393/Rideable#76]
Tokens pass through walls when mounted on a token with piloting option enabled. 

Only Ridable and routinglib are enabled
FoundryVTT version 12
System DnD 5th Edition

![rideable-wall-bug](https://github.com/Saibot393/Rideable/assets/171273170/c77d21fb-b40a-4de8-9ac4-c4dff4b1e95b)

**Comment by Saibot393** [comment]
I have added a collision check with v3.0.1

**Comment by zeleni3** [comment]
It is still possible to enter a wall from the side if it is lined up with the center of the token. 

![rideable-wall](https://github.com/Saibot393/Rideable/assets/171273170/5384b4a4-def9-46db-bf99-4be6a3feed71)

**Comment by Saibot393** [comment]
That should now be fixed with v3.0.2

**Comment by zeleni3** [comment]
You can still enter a wall but now you get stuck inside and can only exit from one of the end points.

**Comment by Saibot393** [comment]
Entering the wall is also possible in core foundry, i don't think there is much more i can do about that. I will try to see what i can do about getting stuck though

**Comment by zeleni3** [comment]
In core foundry it is possible to enter a wall in a similar way but the token is still on one side and is unable to see or pass through to the other side.
Honestly, how it was in v3.0.1 was pretty good already in my opinion. It was a minor issue and also easy to work around. And if it still happens, it will usually only be in a situation where the riding player already had access to both sides of the wall anyways.

**Comment by Saibot393** [comment]
I tried another version with v3.0.3. It should now be almost impossible to enter a wall with piloting. I have also added a per tile/token setting to enable/disable the collision (default off for tokens), since i realised, that the collision check might cause problems for token attacher tokens with attached walls

**Comment by Saibot393** [comment]
Glad to hear that
