### ISSUE TITLE
Rider positioning not working

### ISSUE THREAD

**Issue by Valackus** [Saibot393/Rideable#77]
So, I'm using the module to build moving tiles for my maps like rotating bridges and stuff but after the latest update 3.0.3, every time I mount tokens to a tile it sends them to the top left corner by default, I tried reconfiguring the settings, selecting Rider positioning: "Mounting position" but it does nothing. Is there any other way to make the tokens stay where they are at the moment of mounting or is this a bug? I'm runnning Foundry VTT v11, stable build 315.

**Comment by Saibot393** [comment]
Could you send me screenshot of the tiles rideable settings? Also, which version of rideable and foundry are you using?

**Comment by Valackus** [comment]
Yes! Of course. Also version of Rideable is 3.0.3 and Foundry VTT V11 stable build 315 as shown in the screenshot. Thanks in advance! This is such a cool module. First image is the Tile settings and the rest is the general module settings. 
![image](https://github.com/Saibot393/Rideable/assets/165767246/9d6bd6df-666c-4dcc-8f5d-9bd898762c20)
![image](https://github.com/Saibot393/Rideable/assets/165767246/9e259024-b064-4366-9c26-e6c0821b227e)
![image](https://github.com/Saibot393/Rideable/assets/165767246/7500b6cc-5426-44a3-bfa9-37c01419623d)
![image](https://github.com/Saibot393/Rideable/assets/165767246/2b41b5c1-ab94-4d72-9c9f-f9244efe02dc)
![image](https://github.com/Saibot393/Rideable/assets/165767246/b47976d0-d8c7-401b-945c-a363a8e0027a)

**Comment by Saibot393** [comment]
I solved an issue with v3.0.4 that may have solved this bug. Should that not be the case, could you send me the scenes .json export?

**Comment by Valackus** [comment]
v3.0.4 solved the issue. Thanks a lot! Everything works like a charm now.

**Comment by Saibot393** [comment]
Glad to hear that
