### ISSUE TITLE
Incorrect rider offset

### ISSUE THREAD

**Issue by LordCracken** [Saibot393/Rideable#80]
Hello. I installed Rideable on Foundry v12 on a DnD 4 system. Mounting goes well. If you control the rider as a GM, the rider and horse are controlled as they should. If you control the rider as a player, the horse moves, but the rider is constantly thrown somewhere. The problem is definitely not in the browser. What could be the problem? Could this be a module bug?

**Comment by Saibot393** [comment]
Could you send me screenshot of the ridden tokens rideable settings and of the players rideable client settings?

**Comment by LordCracken** [comment]
The problem only exists if the GM is not looking at the table tab (but he is online).

**Comment by LordCracken** [comment]
> Could you send me screenshot of the ridden tokens rideable settings and of the players rideable client settings?

Yes, a few minutes

**Comment by Saibot393** [comment]
What exactly do you mean with the table tab?

**Comment by LordCracken** [comment]
> Could you send me screenshot of the ridden tokens rideable settings and of the players rideable client settings?

![image](https://github.com/user-attachments/assets/d37415b1-881c-449e-84d4-c266b8d35704)
![image](https://github.com/user-attachments/assets/13943e3a-8334-42ab-9e2c-2ab96d945634)

**Comment by LordCracken** [comment]
> What exactly do you mean with looking at the table tab?
I installed Foundry on a remote server and open it through a browser. If the Foundry tab is the current for the GM, there are no problems. If the GM switches to another program, for example, players will have a strange time moving the rider

**Comment by LordCracken** [comment]
Thank you for your answer. I used Google Chrome (for GM) and Mozilla Firefox Developer Edition (for Player). The GM account was online anyway but the GM not always had the Foundry tab active.

When I turned both browsers in window mode always worked fine. If I return Firefox in fullscreen mode the problem had returned.

**Comment by LordCracken** [comment]
> are there any errors when moving the rider either in the players of the GMs console (F12)?

Error: You are accessing TokenDocument#actorData which has been migrated to TokenDocument#delta
Deprecated since Version 11
Backwards-compatible support will be removed in Version 13

Not sure if this applies to Rideable

**Comment by Saibot393** [comment]
Might be related to rideable but should not have any relevance for this bug. If that is the only error/warning in the console, then i fear that it is really a browser related problem, i.e. the browser freezes the tab. I can sadly not really do anything about that, sorry.

**Comment by LordCracken** [comment]
Thanks again for your answer. At least I was able to understand what actions lead to the problem and how to avoid it.
