### ISSUE TITLE
[Question] How to stop familiar from following?

### ISSUE THREAD

**Issue by TrofimSelbs** [Saibot393/Rideable#81]
Sorry for asking in the Issues, but I can't find a way to get familiar off of the token once it is up there. 
What I tried:
- read wiki
- used unmount hotkey
- used unmount macro
- used familiar hotkey

Nothing is helping. Could you please let me know how is it supposed to be done? Thank you

**Comment by Saibot393** [comment]
The methods you described should all allow you unmount a token that is familliar riding. Notice, that to unmount a familiar you have to either control the familiar or control the master and target the familiar.

**Comment by TrofimSelbs** [comment]
Thank you! I needed to choose them in the correct order
