### ISSUE TITLE
Rider movement default setting issue

### ISSUE THREAD

**Issue by Arthil11** [Saibot393/Rideable#83]
Foundry v12.330
Pathfinder Second Edition v6.1.3

When set to "Move ridden Token (if owned)", if a 2x2 token is mounted the movement with WASD becomes very odd. Movement  done with D moves up, A moves up/left diagonally, S moves left and W also moves up/left diagonally. I'm receiving no errors, and have tested with only Rideable enabled. This is with default settings for rider positioning and token form.

**Comment by Saibot393** [comment]
Should now be fixed with v3.0.5
