### ISSUE TITLE
Buggy Keyboard Movement

### ISSUE THREAD

**Issue by Dr-SaileZ** [Saibot393/Rideable#87]
https://github.com/user-attachments/assets/04709f77-d4b9-4fb8-8d4a-b60cefa691e7

Im just pressing a direction on my keyboard to move the token, the only way to fix it is playing as the GM, Assistance GM has the same problem.

Dragging the Token Still Works normally.

**Comment by Saibot393** [comment]
Could you send me a screenshot of the mounts rideable settings?

**Comment by Dr-SaileZ** [comment]
![image](https://github.com/user-attachments/assets/b63acc43-f226-4d4f-bb87-008816f07972)
Thanks for the quick response, Ive already tied changing basically everything here

**Comment by Saibot393** [comment]
I can currently not replicate the behaviour, a few questions:

- While testing as a player, were you also logged in as a GM?
- Could you send me screenshots of your rideable settings, especially the client settings of the player account you used for testing
- Is that a map with or without grid?

**Comment by Dr-SaileZ** [comment]
- It happend Both While a GM was logged in as well as why I was only logged in as a player.
- The Client Settings from the other Players are all standart.
![image](https://github.com/user-attachments/assets/d11133f5-0173-462a-8f1c-bd286ca92437)
![image](https://github.com/user-attachments/assets/c4294257-0800-46da-9ed7-0856c90933ab)
![image](https://github.com/user-attachments/assets/6c730bbc-b60e-494b-91ee-92b1d7ff5bd7)

- it happens with Grid Without, and also with all kinds of Hexagon
- I did in the video, but Ive also tested it in a new world, with only the rideable module. It does not seem to effect it.

Thanks for your hard work, but maybe its just a me problem. 
But Ive also reinstalled, foundry and the modules. 
So if you got any other Tips.

**Comment by Saibot393** [comment]
Still no luck replicating the bug, few more things i can think of:

- Which system and which foundry version are you using?
- Since it only happens when using the keyboard, what type of keyboard layout are you using?
- Does using the arrow keys to control the token change anything?
- Are there any errors in the console when moving the token (either for the player or the GM)?

**Comment by Dr-SaileZ** [comment]
OK, What im about to tell you probably sounds crazy, but I found the problem or how to fix it (Kinda). 

The issue only happens If I have the second foundry game open on the same monitor, it doesn't matter that one is minimized.

To see the console while testing I had to have both open, and since you cant put foundry on half a screen, I had to use a second monitor. And that fixed it. As soon as I drag it back onto main Main Monitor it breaks again, and if I drag the Programm onto the second it also stops.

**Comment by Saibot393** [comment]
I assume it is the GM instance that is behind the player instance? If so, are you using the Foundry server programm to log in as the GM or are you using another tab?

**Comment by Dr-SaileZ** [comment]
Im hosting foundry from the Programm on my pc and Login into the test player on my browser.

And yeah, this will probably not occur too often in play. And now that I know of it ill keep it in mind.

Thanks For your Help and have a good Day.

**Comment by Saibot393** [comment]
Good day to you too
