### ISSUE TITLE
[Feature Request] Add Option to Change Ridable Dependency to CPR (Chris Premades)

### ISSUE THREAD

**Issue by TrofimSelbs** [Saibot393/Rideable#88]
Thank you for the great module! With the recent changes to DF Convenient Effects, I was wondering if it would be possible to add an option to change the dependency of Ridable from Convenient Effects (CE) to Chris Premades (CPR). Currently, there's no way to add riders, familiars, or grapple functionality if CE isn't active.

Thanks in advance!

**Comment by Saibot393** [comment]
Glad to hear that you like the module.
I am currently actively developing a compatibility update for CPR. I can not yet guarantee when it will be done since there are a few other features I also want to add with the same update but it shouldn't be too long.

**Comment by Tymofii-Vdovychenko** [comment]
Thank you for the response! This is really good news

**Comment by TrofimSelbs** [comment]
This is good news! Thank you for the hard work

**Comment by Saibot393** [comment]
I finally got around to finishing the compatibility update (v3.1.0)

**Comment by TrofimSelbs** [comment]
Thanks! Really appreciate it
