### ISSUE TITLE
Fr translation

### ISSUE THREAD

**Issue by wirgeen** [Saibot393/Rideable#90]
Hello,
As a French user, I propose the French translation of your English file so you can integrate it into your "Rideable" module.
I tested it locally to make sure everything was okay before giving it to you.

Looking forward to it!

[fr.json](https://github.com/user-attachments/files/18176951/fr.json)

**Comment by Saibot393** [comment]
Thank you very much, i will quickly release an update including the translation

**Comment by Saibot393** [comment]
I have released your translation with v3.1.1, thanks again, much appreciated.
