### ISSUE TITLE
[Bug] Grapplee is lagging behind

### ISSUE THREAD

**Issue by TrofimSelbs** [Saibot393/Rideable#91]
Hi! Thank you for your module! I am having an issue with grappling. The grapplee is never carried along with the grappler. It will only do so when the grappler has moved a second time. Please see the video below.

 I am using a simpler movement calculation method (chosen in ridable settings). I don’t use DFreds and I have tried the same with all modules except for Rideable turned off

https://github.com/user-attachments/assets/7b9578c6-2d62-4a57-aedd-dd96a8f6b373

**Comment by Saibot393** [comment]
I will look into it, might take a few days though

**Comment by TrofimSelbs** [comment]
Thank you 🙏 Let me know if I can give any more info

**Comment by Saibot393** [comment]
The bug should now be fixed with v3.1.2
